lua/plenary/job.lua
This seems to fix the issue with [Telescopes](https://github.com/nvim-lua/telescope.nvim) `live_grep` on Windows 10, for some reason if we pass a `stdin` handle but never write to it, the process hangs and never returns. This might only happen in some scenarios since output was already working for other jobs for example `find_files`, I tested both using `rg` as a backend.
I don't see why a job that isn't writing anything would need a `stdin` handle open, so this seems like a safe change?
=> Only create stdin handle if job is a writer

lua/plenary/job.lua
[uv.write](https://github.com/luvit/luv/blob/master/docs.md#uvwritestream-data-callback) appears to be non-blocking so we need to make sure not to close the pipe until writing has done.
=> fix: close stdin pipes in callback

lua/plenary/job.lua, tests/plenary/job_spec.lua
Check if o.command exists before creating a new job. If not adds a debug traceback. Example: "rg: Executable not found"
=> telescope #369: added stack traceback for no finder

lua/plenary/path.lua, lua/plenary/scandir.lua, tests/plenary/scandir_spec.lua
todo:
Quick comparison with neovim repo (more will come) (all results are in seconds):
|               | fd       | rg --files | lua sync | lua async |
|---------------|----------|------------|----------|-----------|
| neovim/neovim | 0.004374 | 0.003067   | 0.004353 | 0.006484  |
current `m.ls` output from telescope with hidden:
```
drwxr-xr-x  4.0K conni conni  Jan 11 16:04  .git
drwxr-xr-x  4.0K conni conni  Jan 11 13:04  .github
-rw-r--r--   7.0 conni conni  Jan 11 13:04  .gitignore
-rw-r--r--   619 conni conni  Jan 11 13:04  .luacheckrc
-rw-r--r--  1.0K conni conni  Jan 11 13:04  LICENSE
-rw-r--r--   190 conni conni  Jan 11 13:04  Makefile
-rw-r--r--   33K conni conni  Jan 11 16:00  README.md
drwxr-xr-x  4.0K conni conni  Jan 11 13:04  data
-rw-r--r--  3.9K conni conni  Dec 19 19:41 …
```
=> In lua find using `vim.loop.fs_`

data/plenary/filetypes/builtin.lua
This adds `dart`,`kotlin`,`gradle/groovy`,`plist` files to the list of filetypes used for detection so it can be recognised correctly by `telescope`'s buffer previewers.
=> Add more filetypes for filetype detector

README.md, lua/plenary/job.lua, tests/plenary/job_spec.lua
Builds on top of your previous work for `and_then`. We might also wanna change `chain` i my opinion it has the even better interface to do that.
None of these additions are necessary but after i saw @tami5 code it might be helpful. tami is currently in the `on_exit` callback hell which makes maintaining his work a nightmare, no offense tami :). This might help writing jobs that go from job to job easier.
Example at the end. For me that is easier to read and i actually know when which job does what and what the conditions are for that case to happen. Does this make sense? We do not need to integrate it :)
I only want that `sync` returns the result code. Thats the only thing that interests me tbh :rofl: Saves me one line in telescope.
Adds:
- `sync` will now return `code` as second return …
=> Introduces a range of `and_then` and `after` function that will handle callbacks

README.md, lua/plenary/busted.lua, tests/plenary/simple_busted_spec.lua
Just a sketch. ~~I probably need to do something a little smarter. But i am tired right now, so i will finish it tomorrow :)~~
Edit: `after_each` could also be helpful. Any thoughts tj? Or whats suggested here: https://github.com/nvim-lua/plenary.nvim/issues/49#issuecomment-761623782
Thats the idea, because tami asked 😆 :
```lua
describe('main', function()
it('stuff 0', function() end) -- will not run any before_each
describe('nested', function()
before_each(clear)
it('stuff 1', function() end) -- will run clear
describe('nested nested', function()
before_each(del_db)
it('stuff 2', function() end) -- will run clear and del_db
end)
it('stuff 3', function() end) -- will run clear
end)
it('stuff 4', function() end) -- will not run any before_each
end)
```
=> busted before_each and after_each

lua/plenary/path.lua, tests/plenary/path_spec.lua
I'm working on moving telescope to use `plenary.path` instead of its own path module (see [this issue](https://github.com/nvim-telescope/telescope.nvim/issues/387)) and found that there were some functions missing in plenary.
Functions I added:
-  `Path:normalize`
-  `Path:make_relative`
-  `Path:read_async`
I also added the property `home` to `Path.path`, which is simply the user's home directory. It can probably be used in places other than the functions for which I added it, but I did not go through and apply it in those spots yet.
CC @Conni2461
=> Add functions from telescope.path

README.md, lua/plenary/path.lua, lua/plenary/scandir.lua
Also:
- Group directories first
- update gen_date so it will show %b %d $Y if last modified is not from
this year
- Bug fix for symbolic links
- Show resolved symbolic link, like this:
a -> b
- Correctly align user and groups. So should align like this:
```
conni    conni     DATE
root     root      DATE
asdfasdf asdfasdf  DATE
```
=> Calculate each section when generating string

lua/plenary/busted.lua, lua/plenary/job.lua, lua/plenary/test_harness.lua, tests/plenary/simple_busted_spec.lua
Currently only one top level describe is possible. We talked about that already. That should fix it.
Also pending will also print the current stack now not only the message.
Also also i moved some of the before and after each in its own top level describe block and added a fourth one for testing. So it should work :)
~~Edit: The fatal thing is not working so i gotta fix that first :rofl:~~
I am not so sure if i like the new fatal handling so far. Maybe we should just do if `inner` not okay then print error and stop execution.
~~Also we are running into this issue where all tests are passing but we are still returning 1 or 2 and it seems like now its more present.~~ I fixed that by having `Job:join` accept a timeout as last param and setting that to 50000. Can't have it behind the unpack. …
=> busted: fix for multiple top level describes

lua/plenary/job.lua
- Avoid using vim.fn where possible.
- Where there is no alternative to the vim.fn function, do something
graceful instead.
=> Allow jobs to be launched in callback threads

lua/plenary/scandir.lua
I thought it would be nice to have an option to suppress the message displayed if access is not possible.
However, this pull request may not be necessary since we only need to check if it is accessible before calling scan_dir().
Therefore, if you do not need it, you may close the pull request.
=> feat: add silent to opts of scan_dir() and scan_dir_async()

lua/plenary/nvim_meta.lua, lua/plenary/popup.lua, lua/plenary/window/float.lua, scratch/window_test.lua
Now that https://github.com/neovim/neovim/pull/13875 is merged, using `vim.fn` when the same function exists in `vim.api` causes an error. I _think_ this PR updates everything that needs to be fixed, but I'm not 100% certain.
=> Prefer vim.api over vim.fn

lua/plenary/path.lua
When using the `Telescope file_browser`, plenary returns the incorrect path separator for BSD operating systems, fix that.
`jit.os` is `BSD` on FreeBSD, take this into account when returning the path separator.
Tested on FreeBSD.
=> path.lua: use correct path separator on BSD operating systems.

lua/plenary/job.lua
If o.cwd is a string to a non-existent path then uv.fs_realpath returns
nil which causes vim.fn.expand to be called which causes an error if
called in a callback thread.
=> Fix path expansion in callbacks

lua/plenary/path.lua, tests/plenary/path_spec.lua
The old `Path:parents()` method was confusing to someone who might have expected that, like in python's pathlib, it return a list of paths, instead of the single path representing the filename of the immediate parent.
The old implementation has been renamed simply to `parent()` and it's usages renamed to reflect that change, and the new implementation returns a list of strings with every ancestor of the original path, including `path.root`
=> Add `path.root` and make `Path:parents()` return a list of paths

lua/plenary/path.lua, tests/plenary/path_spec.lua
I had a problem with telescope where if I gave an explicit trailing slash
to a cwd option, the resulting relative path was incorrect if I was in that
same directory, as it would leave an extra slash at the beginning.
I fixed this locally, but when I wanted to make a PR, I noticed there was
a plan to use the path stuff from plenary, so I fixed it in plenary instead
and added some tests that I had.
I'm not sure if I followed the appropriate (lua) coding guidelines as I'm new
to lua, so please review carefully. I also noticed some of the tests seemed
unix specific, and I'm not sure if that was intentional, but in any case I tried
to keep my tests OS-independent.
I used two extra local functions to be able to handle path names as strings
without having to create a Path object (since I could …
=> fix relative paths with double separators

lua/plenary/path.lua
Windows root paths may be `C:\\` or `C:` and the previous regex logic did not capture this
=> Fixing is_root check for Windows root paths

lua/plenary/async_lib/async.lua, lua/plenary/tbl.lua
Adapt packing and unpacking of arguments passed through the async wrapper to make sure all arguments are passed down to the function, even if some arguments are `nil`.
I'm not familiar with the project structure, so I just put the helper methods into local module scope. Any place they'd be more at home? Maybe exporting them from `tbl.lua`?
Closes #119
=> fix: make async'd function nil-save

lua/plenary/async_lib/util.lua
Reset callbacks as they go to `nil` and leave table intact instead of creating a new table and resetting the variable that held the previous table.
=> fix: condvar tables resetting

README.md
The example command in the README does not work since it gives the error:
```
Error detected while processing command line:
E5107: Error loading lua [string ":lua"]:1: ')' expected near '.'
Press ENTER or type command to continue
```
Changing the quoting as in this PR fixes the error.
=> Fix quoting

lua/plenary/path.lua, tests/plenary/path_spec.lua
think _normalize_path should return absolute path according to absolute()
is that right?
Path:absolute() returns the result of _normalize_path so I would think this change is needed
=> Fix normalize path

lua/plenary/log.lua
Following this in Neovim https://github.com/neovim/neovim/pull/13739 it
probably makes sense to follow suit. I know this may change location for
some that are already using this, but it does seem logical to move this
here since other log files are also being placed here.
=> Change log location to cache to align with NeoVim.

lua/plenary/functional.lua, lua/plenary/test_harness.lua
`fun` is more fun than `f`
The implementations are slightly different (`vim.tbl_map` preserves the keys,
and doesn't do an implicit transformation to a list like table)
The `iter` argument name to me also implied that it would take a function
following the lua iterator protocol but that wasn't the case.
Motivation was mostly that I asked myself what's special about `f.map`  while reading some test_harness code
(Not sure if this is okay, as it breaks the API?)
=> Replace f.map with vim.tbl_map

lua/plenary/test_harness.lua
This supports setups where `nvim` is *not* a 0.5 nvim, but where the
test run is started using a different program path, for example using an  alias.
Previously `v --headless [...] -c "PlenaryBustedDirectory [...]"`
failed:
testing: 	[...]/tests/manual/large_job_spec.lua
========================================
FAILED TO LOAD FILE
stack overflow
========================================
Here `v` is a alias pointing to a development build of neovim with
`$VIMRUNTIME` set appropriately.
=> Use vim.v.progpath to spawn busted test runs (fixes stack overflow)

data/plenary/filetypes/builtin.lua
There is no default [ftplugin](https://github.com/neovim/neovim/tree/master/runtime/ftplugin) for [nix](https://nixos.org/manual/nix/stable/) but with plugins like [vim-nix](https://github.com/LnL7/vim-nix) it is supported and needs to be verbosely added to plenary.
=> Add nix extension

lua/plenary/path.lua, lua/plenary/scandir.lua
If ober is reading this: i will not refactor this with async await (i don't have the time for that). I am just here fixing that small bug.
See https://github.com/nvim-telescope/telescope.nvim/issues/802#issuecomment-828197581
=> fix: clean up hanging file handles for head/tail

lua/plenary/window/float.lua
I've found that when creating these I sometimes want to create it right away with
a title. This small change just adds another parameter to `percentage_range_window`
allowing the user to pass in border options. This is then just passsed in when
the border is created.
=> Allow for border options to be passed in to percentage_range_window.

README.md, lua/plenary/strings.lua, lua/plenary/window/border.lua, tests/plenary/strings_spec.lua
ref #95
ref https://github.com/nvim-telescope/telescope.nvim/pull/464
=> Add `strings` module

lua/plenary/path.lua
Fixes current situation where `path.shorten` function may not return anything
=> Fix `path.shorten` returning `nil`

lua/plenary/scandir.lua
Currently, directories are always added to `scan_dir` results when `add_dirs = true`. This PR makes `respect_gitignore` behavior consistent for files and directories. 
It also appends `/` to the entry to handle gitignore directory patterns. This makes it so that that the gitignore patterns `/node_modules`, `node_modules`, and `node_modules/` (all of which, according to [the documentation](https://git-scm.com/docs/gitignore), are valid, with slightly different interpretations) will all correctly match the entry `/path/to/node_modules`. 
(I wanted to add a test but wasn't sure how to do so without modifying the project's `.gitignore` file, which seemed like a bad idea, so let me know.)
=> fix: apply respect_gitignore to directories

data/plenary/filetypes/builtin.lua
I just started using telescope and noticed that eruby doesn't have syntax highlighting in preview. This change fixes that.
=> Add eruby filetype

data/plenary/filetypes/builtin.lua
I am aware of https://github.com/nvim-lua/plenary.nvim#plenaryfiletype and I added fish as a extension manually. However, if I were to add the shebang manually I would also have to add more than one line because of all the prefixes.😁
=> Add fish to filetypes shebangs table

lua/plenary/path.lua, tests/plenary/path_spec.lua
make_relative would falsely produce `bar/file.txt` when
making `/tmp/foo_bar/file.txt` relative to `/tmp/foo` because of the
partial match
Minimal repro:
```
:lua print(require'plenary.path':new("/tmp/foo_bar/b"):make_relative("/tmp/foo/"))
```
Originally found in https://github.com/nvim-telescope/telescope.nvim/pull/913
=> fix: make_relative didn't check for path_sep after cwd

lua/plenary/curl.lua, tests/plenary/curl_spec.lua
Hey all!
at first: let me thank you for this awesome library!
I found a bug while trying to pass a string as body to the cURL wrapper.
As we can see in [this line](https://github.com/nvim-lua/plenary.nvim/blame/22127c47454e3b09be38b3a4bbe3edf42e7b3fc7/lua/plenary/curl.lua#L142) the argument for passing extra command line arguments to curl was named `raw_args` and [the option](https://github.com/nvim-lua/plenary.nvim/blame/22127c47454e3b09be38b3a4bbe3edf42e7b3fc7/lua/plenary/curl.lua#L137) for setting the raw body was named `raw`.
As we can see in [this commit](https://github.com/nvim-lua/plenary.nvim/blob/08c0eabcb1/lua/plenary/curl.lua#L171) by @tami5 it changed. The name for the option for passing extra arguments to cURL was renamed to `raw`!
Source: …
=> [BLOCKER] Fixed raw body passing for the cURL wrapper

lua/plenary/job.lua
Whilst developing a plugin using plenary's job module I added plenary to my `sumneko_lua` workspace library using
```lua
settings = {
Lua = {
workspace = {
library = {
[path_to_plenary] = true
}
}
}
```
I find the type annotations very helpful in my project since I can import the type via
```lua
---@type Job
local Job = require('plenary.job')
```
Unfortunately the type annotations seem to be misplaced i.e. the `new` function is annotated rather than the actual class object that is exported. This means that the exported types has none of the correct methods. By moving the annotation to the declaration of `Job` this is now recognised correctly.
NOTE: the `new` function is just a function so annotating it doesn't apply the types to the object it returns given the object itself isn't typed
=> Move type annotation to the Job class definition

lua/plenary/async/async.lua, lua/plenary/async/util.lua, lua/plenary/vararg/rotate.lua, scripts/vararg/rotate.lua, tests/plenary/async/async_spec.lua
```
- Allow wrapped functions to be called with less arguments then they
were defined with.
- Reimplement void()
```
There were the changes require to get gitsigns working with the new lib.
=> Fixes for async2

README.md, lua/plenary/profile.lua, lua/plenary/profile/p.lua
This is a thin wrapper around LuaJIT's `jit.p` with the right "magic" options set. Only configuration right now is `flame=true` to output flamegraph-compatible logs; see https://github.com/jonhoo/inferno
to be used with
```
inferno-flamegraph profile.log > flame.svg
```
The SVG file can then be viewed in the browser.
This commit includes a vendored version of the latest upstream `jit.p` that fixes a bug with flushing the output file; once https://github.com/LuaJIT/LuaJIT/commit/95140c50010c0557af66dac944403a1a65dd312c is pulled in, this file can be removed.
More configuration options are left for a future PR.
Thanks to @leiserfg for showing me how to actually get this working!
=> feat(profile): add wrapper around LuaJIT profiler

lua/plenary/path.lua, tests/plenary/path_spec.lua
=> Make Path:parent() return a Path object instead of a string

lua/plenary/path.lua
We have two `Path:is_file()` methods defined:
1. https://github.com/nvim-lua/plenary.nvim/blob/8bae2c1fadc9ed5bfcfb5ecbd0c0c4d7d40cb974/lua/plenary/path.lua#L503-L505
2. https://github.com/nvim-lua/plenary.nvim/blob/8bae2c1fadc9ed5bfcfb5ecbd0c0c4d7d40cb974/lua/plenary/path.lua#L541-L546
Any reasons to keep both?
=> fix(path): remove duplicate function definition

lua/plenary/path.lua
This PR gets rid of an unnecessary print statements which is annoying if you want to do something like `tostring(path)`
It's needed for a big fix PR of telescope-project 
https://github.com/nvim-telescope/telescope-project.nvim/issues/58#issuecomment-890568732
=> removed unnecessary debug print() in path.lua

lua/plenary/log.lua
Adds backslashes to the list of characters to escape in log messages.
Previously had issues when file paths contained backslashes (which is a particular problem on windows).
=> fix: escape backslashes in `plenary.log` messages

tests/plenary/job_spec.lua
Add tests for the situation where the command output does not have
an ending newline. The first test shows what happens when the newline is
output, the second test shows what happend when the newline is not
there.
=> feat(job): add tests for missing ending newline in command output

lua/plenary/json.lua, tests/plenary/json_spec.lua
this PR adds an utility method to strip comments from json strings so the resulting string can be loaded with `vim.fn.json_decode`.
JSONC is used by vscode and others to allow having comments inside JSON files.
The PR is a Lua port of [strip-json-comments](https://github.com/sindresorhus/strip-json-comments)
All the test cases have also been ported.
```lua
local json = require("plenary.json")
local str = [[
{
// this is a comment
"a": 123, // foo
/* a multi
line
comment
*/ "b": 222
}
]]
local stripped = json.json_strip_comments(str)
local obj = vim.fn.json_decode(stripped)
print(vim.inspect(obj))
```
This will print:
```lua
{ …
```
=> feat: added json_strip_comments

plenary.nvim-scm-1.rockspec
The module path has changed in commit 5e5c87fcc3ba88ade64210a870690e803931ffb7 but the rockspec hasn't, so currently the luarocks package is broken. This fixes it.
=> rockspec: fix module path

POPUP.md, lua/plenary/popup/init.lua, lua/plenary/window/border.lua
As per this [vim issue](https://github.com/vim/vim/issues/5737) `noautocmd` is the default for popups (couldn't find it in docs), which now is configurable via `vim_options.noautocmd`.
cc @l-kershaw
=> fix: default to noautocmd for popup like vim

README.md
=> docs: update neogit mention under async

lua/plenary/popup/init.lua, lua/plenary/window/border.lua
Adds options `focusable` and `border_focusable` in `popup` (and `focusable` in `Border`) to change whether user window actions can focus the content window and popup window.
To match popup behaviour from vim, the defaults for both are false, which may break some plugin use cases (doesn't seem to break Telescope in my quick tests, but we should still specify the behaviour we want over there).
=> feat: add options for popup being focusable

POPUP.md, lua/plenary/popup/init.lua, lua/plenary/window/border.lua
This is an updated version of [this](https://github.com/nvim-lua/popup.nvim/pull/17).
I was expecting to need to subtract 1 when setting the border zindex, but it _seems_ to work fine being set the same.
=> feat: popup and border zindex

README.md
Forgot to update the readme to reflect the new test harness option.
=> Update README with information about test harness timeout option

lua/plenary/benchmark/init.lua, lua/plenary/benchmark/stat.lua, lua/plenary/test_harness.lua
Trying to add a way in which we can tests the performance and improve it. I'd like to have this be part of busted run test output somehow. maybe through a global variable 'bench_run', 'bench_compare'
example:
```lua
becnh_run("predicting y", {
warmup = 4, -- number of runs before start calculating
runs = 100, -- number of runs 
fun = function()  -- function to test
vim.wait(400, function() end)
end
})
```
output 
```lua
("predicting y") Benchmark:
- total elapsed time: 492591167.000ms
- runs: 100
- min: 5031917.000s, max: 492584084.000s, mean: 247768180.710s, median: 246534042.000000s, std: 142929375.485669s
```
not sure how to do compare yet
=> feat(benchmark): add util to benchmark functions

lua/plenary/strings.lua, tests/plenary/strings_spec.lua
Allows optional `direction` for `truncate`, where >0 truncates from the right and <0 truncates from the left.
Could be used for truncation of paths in telescope, as requested [here](https://github.com/nvim-telescope/telescope.nvim/issues/1167#issuecomment-918298987).
=> feat: allow truncation of strings from left

POPUP.md, lua/plenary/popup/init.lua, tests/plenary/strings_spec.lua
Heavily based on the implementation from [this PR](https://github.com/nvim-lua/popup.nvim/pull/9) by @jesseleite.
Also, added options to center in only one direction using `0` for `row`/`line`.
This required shifting the indices of everything else by one, which is a bit annoying, but this is how the implementation in vim works, so 🤷
This does break stuff in telescope, so I will write a PR over there when I get a chance.
=> feat: allow `pos="center"`, `row=0`, `line=0`

lua/plenary/window/border.lua
Fixes GH-239
* Modify the `if` statement checking that the row is positive and non-zero for a `Border`, by allowing negative values for cursor-relative row numbers, if they are not outside of bounds
* Add an `else` branch to remove top border thickness if the `topline` should not be drawn
As described in GH-239, this commit aims to fix an issue with the Border component, which makes it impossible to draw the top and bottom lines and makes the middle line replace the former, if the row is a negative value. This also makes it impossible to use the `planery.popup` cursor-relative positioning, as a value such as 'cursor-2' would break the popup.
Tests from the `tests` and `lua/luassert` directories are used for validation, as I am not too familiar with the current code base. If others should …
=> fix(border): Failing to display if row negative

lua/plenary/path.lua, tests/plenary/path_spec.lua, tests/plenary/strings_spec.lua
Allows you to specify certain positions that are excluded when shortening a path.
Currently when shortening a path, we shorten every section of the head of the path, leaving the last section (the tail) alone. This PR allows you to specify which positions you want to exclude from the shortening, by giving a list of positions.
For example:
- using `exclude={-1}` gives the default behaviour mentioned above
- using `exclude={1,-1}` shortens every section of the head of the path, apart from the first one
- using `exclude={2,-2}` shortens every section of the path apart from the 2nd from the beginning, and second from the end (so this will shorten the tail of the path unless the path has exactly two parts)
Inspired by [this](https://github.com/nvim-telescope/telescope.nvim/issues/880) issue in …
=> feat: exclude positions in `Path:shorten`

lua/plenary/window/border.lua
This is a follow on PR from #240.
With the current implementation of popups, you get weird artifacts when drawn right at the boundary of the editor.
#240 fixed this for the top of the screen.
This PR fixes this for the:
---
I am unsure of how to implement a fix for the left/right of the screen, when using positioning relative to the cursor.
This is due to the fact that you can't directly translate cursor position relative to window into cursor position relative to editor.
The part I am stuck on is incorporating the width of the sign/number columns, as they shift everything horizontally, and I can't see a way of checking their size.
=> fix: remove edge of border when drawn at the boundary

lua/plenary/window/border.lua
=> fix: correct position of `titlehighlight` when top border disabled

lua/plenary/strings.lua, tests/plenary/strings_spec.lua
Thought it might be useful to truncate strings from the middle.
Currently a bit of a rushed draft, and just guessed what the new tests should be (haven't actually run them yet 😅).
I will have another look over it in the next few days.
=> feat: truncate strings from the middle

lua/plenary/path.lua, tests/plenary/path_spec.lua
Extends `Path:copy` to recursively copy folders for https://github.com/nvim-telescope/telescope.nvim/pull/1257
This is pretty much the plenary equivalent of how nvim_tree performs copying [here](https://github.com/kyazdani42/nvim-tree.lua/blob/d7f73b5ae9c8fa85535c32e2861c2cb97df5d56b/lua/nvim-tree/fs.lua#L146).
E: tests are TODO
=> feat: copy directories recursively

lua/plenary/window/border.lua
Previously would reset the position `pos` to `N` later on in `Border._create_lines` when calling `Border:change_title`. 
```lua
-- border_win_options.title should have be a list with entries of the
-- form: { pos = foo, text = bar }.
-- pos can take values in { "NW", "N", "NE", "SW", "S", "SE" }
local titles = type(border_win_options.title) == "string" and { { pos = "N", text = border_win_options.title } }
or border_win_options.title
or {}
```
Was causing issues in certain `telescope.nvim` applications (https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/41#issuecomment-1004262654) where a title with `pos = "S"` was disappearing since the `pos` was being overwritten upon a `change_title` call.
My change should enable the retaining of `pos` or the explicit changing of it.
=> fix: allow border title position change/retaining

lua/plenary/window/border.lua
Better conditional for checking title position.
Came up due to downstream issue with Telescope.nvim that appeared with [latest commit](https://github.com/nvim-lua/plenary.nvim/commit/6d54c198a785131532de77978523c5f1e429d1e6).
=> fix(window): accessing potentially empty border title index

lua/plenary/job.lua
Add the field `detached` to the job object to allow for spawning jobs in
a detached state. This passes `options.spawned` to `uv.spawn` which
causes the child process to become a process group leader allowing it to
persist after the parent process exits.
Addresses #311
=> Allow jobs to spawn detached

lua/plenary/reload.lua
This adds support for `-` in module names.
=> fix: escape module names in reload.reload_module()

lua/plenary/job.lua
`job:shutdown()` raises an error if called without a `_shutdown_check` running.
From what I experienced that is basically always the case.
This just checks if `_shutdown_check` is nil before passing it to `vim.loop.is_active`
=> fix(job): shutdown raises error

lua/plenary/filetype.lua, lua/plenary/path.lua, tests/plenary/path_spec.lua
Filetype detection used to read the first line for shebang and the last
line for modeline detection. This was really slow with large binary
files that don't contain newlines.
Add Path:readbyterange(offset, length) to allow reading a specific range
and reimplement detect_from_modeline and detect_from_shebang to work
with the first 256 and last 256 bytes of a file.
Fixes #307 and closes #322.
=> fix: filetype detection freeze with binary files

lua/plenary/path.lua, tests/plenary/path_spec.lua
This aims to fix problems seen in #330.
1. double-slash at the front for tilde-subbed home paths
2. extra `./` in the middle of a path
=> fix: plenary.path normalize

lua/plenary/async/init.lua, lua/plenary/async/tests.lua, tests/plenary/async/test_spec.lua
Useful when setup/teardown function are asynchronous.
=> Add before_each, after_each for async tests.

lua/plenary/path.lua, tests/plenary/path_spec.lua
Usernames with dashes at the end are perfectly valid unix user names, but they're seen as a regular expression pattern in Lua. Switch to using string.find instead of string.gsub to avoid the pattern matching issue.
Further solves https://github.com/nvim-telescope/telescope.nvim/issues/1521 for me
=> fix: path normalization works with esoteric usernames

lua/plenary/busted.lua, lua/plenary/test_harness.lua
This allows the running neovim instance to clean up resources before exiting, for
example terminating running LSP servers.
=> fix(tests): use :cq instead of os.exit()

data/plenary/filetypes/base.lua
[ClojureDart](https://github.com/Tensegritics/ClojureDart) released several days ago. 
Found this repo in telescope docs:
```
Note: if plenary does not recognize your filetype yet
1) Please consider contributing to:
$PLENARY_REPO/data/plenary/filetypes/builtin.lua
```
So making this pr.
=> feat: add clojure-dart filetype

lua/plenary/path.lua, tests/plenary/path_spec.lua
Scenario:
home: /home/foo
file: /home/foobar/baz.txt
normalize returned ~/bar/baz.txt instead of /home/foobar/baz.txt
=> fix (path:normalize): handle filenames with the same prefix as the home directory

lua/plenary/curl.lua
When doing curl request with body which contain `$` the error is encountered because `Path` tries to expand `$`:
```
Traceback: ...site/pack/packer/start/plenary.nvim/lua/plenary/path.lua:311: Path not valid
```
I would say this fixes also https://github.com/nvim-lua/plenary.nvim/issues/299.
=> fix curl check if body string is file - "Path not valid" error if body contains $

lua/plenary/path.lua
Reduces `Path:new` to c. 1/3 of cost. Can be quite relevant for `telescope` finders that more greedily create `Path`s. Just thought I'd put this up for discussion.
```lua
local bench = require "plenary.benchmark"
local Path = require "plenary.path"
-- /home/fdschmidt/repos/lua/telescope-file-browser.nvim/
local filename = vim.api.nvim_buf_get_name(0)
bench("Path", {
warmup = 10,
runs = 50,
fun = {
{
"Path creation",
function()
for _ = 1, 1000 do
Path:new(filename)
end
end,
},
},
})
```
Before
Benchmark Group: 'Path' -----------------------                                                                                                                                                 
Benchmark 1: 'Path creation' …
=> feat: defer libuv calls in Path:new

lua/plenary/context_manager.lua, tests/plenary/context_manager_spec.lua
This more closely emulates the behavior of the Python `with` statement,
which according to comments this is modeled off of.
With this change the context will always be closed, even if an error
occurs. This means that, for example, you can open a file without having
to worry about an error leaking the file handle. Or if you created a
context for creating temporary files and deleting them when done, you
wouldn't need to worry about failing to delete the temp file.
This change also re-enables disabled `context_manager` tests.
Fixes #340
=> Handle errors in callback passed to `context_manager.with`

lua/plenary/path.lua
Steps to reproduce:
`nvim -u init.vim`
init.vim
```
set runtimepath^=plenary.nvim
lua require('b')
```
b.lua
```
local Path = require('plenary.path')
local path = Path:new('C:\\projects\\work\\appcore\\..\\build')
print('filename = ' .. path.filename)
print('absolute = ' .. path:absolute())
```
output
```
filename = C:\projects\work\appcore\..\build
absolute = C:\C:\projects\work\build
```
This happens because on Windows `_split_by_separator` returns one more element, which is a disk name. And function `_normalize_path`  is not ready for that.
I know that I could change `_split_by_separator` behavior, but I decided, what it works correctly and disk name (if present) should be returned.
Also I included fix for `is_absolute` function. I understand, that it might break some plugins, if they …
=> Path:absolute on windows returns double disk name part if path contains ..

lua/plenary/log.lua
On Neovim nightly (currently pre `v0.8`), the log file cannot be created
and writen to since the `.cache/nvim` directory is not created. This is
fixed by checking that the parent of the outfile does not exist and if
it doesn't creating the directory, as mentioned by @Conni2461.
Fixes: GH-367
Signed-off-by: Filip Dutescu <filip.dutescu@gmail.com>
=> fix(log): no file made if no cache dir

plenary.nvim-scm-1.rockspec
the data folder was not copied. Also the 'builtin' type will copy automatically everyhting that is in the lua folder
=> build: improve rockspec

lua/plenary/async/async.lua
Found this while trying to wrap() the vim.ui.input  offered by dressing.nvim, as it actually overrides the value with a table that implements `__call` instead of an actual function.
=> Check for metatable with `__call` when asserting callable status

lua/plenary/test_harness.lua
This is to catch test runs where the process exits erroneously, for
example via a SIGABRT.
I also noticed that spawned jobs are not terminated should the test time out.
=> fix(test_harness): kill job on timeout and check signal for failure on job completion

lua/plenary/test_harness.lua
Currently, when running tests sequentially, the very last spec file that
executes will determine whether a failure has happened or not.
=> fix(test_harness): retain failure status when running tests sequentially

lua/plenary/path.lua
The existing path.sep logic tested explicitly for Linux, OSX, or BSD OSes as queried through LuaJIT (if present).  This left out other POSIX OSes, which will almost certainly use the UNIX-style forward slash, rather than backslash.
Since Windows is the odd one out when it comes to path separators, using it for the comparison should provide better coverage long-term.  If you'd prefer I simply add `posix` to the existing comparison list, I'm happy to update the PR.  I don't have a Windows machine to test one.
=> Correct path.sep for POSIX LuaJIT consumers

.github/workflows/release.yml, Makefile, scripts/luarocks-upload.sh
@Conni2461
see https://github.com/nvim-telescope/telescope.nvim/pull/2276#issuecomment-1368446702.
The upload script expects a `LUAROCKS_API_KEY`. It should be possible to set it as one of this repo's GitHub Actions secrets.
I have tested `make luarocks_upload` and it seems to work, but I cannot test this with GitHub Actions. The lua/luarocks install tasks fail when run locally with [act](https://github.com/nektos/act), but maybe they will succeed on GitHub.
=> ci: add luarocks upload release workflow

.github/workflows/release.yml, Makefile, scripts/test-luarocks-install.sh
@Conni2461 ..and here's the post-release install test :)
=> ci(luarocks-release): add install test

TESTS_README.md, lua/plenary/busted.lua, tests/plenary/async_testing_spec.lua
This has some slight changes of behavior, which I don't think matter:
1. Previously, running `coroutine.running()` inside a test would yield `nil`. Now it yield the thread. If anyone was checking it, it would be different now. Then again - I see no reason why anyone would check it.
2. Previously, running `coroutine.yield()` inside a test would fail. Now it yields. Again - I see no reason why anyone would do this before this PR which adds support to it.
I wanted to add an entry to `CHANGELOG.md`, but it seems unmaintained and irrelevant.
=> Close #424 - make tests run in coroutine to support asynchronous testing

TESTS_README.md
`:PlenaryBustedTest `  
is not a command.
#403
=> docs(tests): fix outdated instructions

lua/luassert/assert.lua, lua/luassert/assertions.lua, lua/luassert/formatters/init.lua, lua/luassert/languages/en.lua, lua/luassert/util.lua
I wanted to update `languages/en.lua` in order to properly fix #376, because last time language file was not updated in #377, but it's required. After this change it looks like this:
```
Fail    ||      plugin/format configure_format sets up format on save for matching client
tests/nvim/unit/plugin/format_spec.lua:98: Function was never called with matching arguments.
Called with (last call if any):
(values list) ((string) 'BufWritePre', (table: 0x7f3b2e6bb060) {
[buffer] = 1
[callback] = function: 0x7f3b2e6b8798
[desc] = 'Format on save'
[group] = 3 })
Expected:
(values list) ((string) 'BufWritePre', (table: 0x7f3b2e6c5180) {
[buffer] = 1
[callback] = function: 0x7f3b2e6c5230
[desc] = 'Format on save'
[group] = 3 })
stack traceback:
tests/nvim/unit/plugin/format_spec.lua:98: in function …
```
=> chore(luassert): bump to v1.9.0

scripts/luarocks-upload.sh
@Conni2461
the upload script's `sed` call replaces `'scm'` in the following section:
```lua
if _MODREV == 'scm' then
source = {
url = 'git://github.com/nvim-lua/plenary.nvim',
}
end
```
This PR makes sure it only replaces the declaration at the top of the file:
```lua
local _MODREV, _SPECREV = 'scm', '-1'
```
=> fix(luarocks-upload): make sure correct archive is uploaded

README.md, lua/plenary/test_harness.lua
Use case: Run tests for neovim derivations packaged with Nix.
See also:
* https://github.com/NixOS/nixpkgs/issues/78033
* https://github.com/MrcJkb/haskell-tools.nvim/pull/93#issuecomment-1374969656
=> feat: allow specifying the binary to launch neovim in tests

lua/plenary/filetype.lua
This is an attempt to fix #450 
Perhaps [related](https://github.com/nvim-telescope/telescope.nvim/issues/1858)
=> fix(filetype.lua): don't fail on empty filepath

data/plenary/filetypes/builtin.lua
Add device tree extension mapping.
`.dts` are recognized fine but not `.dtsi`
=> feat: add dtsi filetype

lua/plenary/test_harness.lua, plugin/plenary.vim
expand() should only be called for the first argument, not for the second one.
The second argument is a string representation of a Lua option table which did work in case of a single entry, where only the braces were removed.
For multiple entries Lua was not able to parse the expanded version as option table anymore, though.
=> Fix PlenaryBustedDirectory command

lua/plenary/curl.lua
Add a new `stream` function option to specify that response data should be streamed to the `stream` function.
An example of this in use:
``` lua
curl.get("https://streaming-url/", {
raw = { "--no-buffer" }, -- optional to indicate that curl shouldn't buffer output stream.  maybe always include this?
stream = function(err, data, job)
vim.pretty_print(data)
end,
})
```
And of course the connection can be closed by calling `job:shutdown()`
=> feat(curl): add support for streaming responses

lua/plenary/job.lua
Currently unable to use `Job` where `cwd` has a `$` symbol as it's being expanded out by `vim.fn.expand`.
This is causing an issue downstream with [telescope-file-browser](https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/244) when fetch git status info using cwd paths like `($lang)/` which is used in [Remix](https://remix.run/docs/en/1.15.0/file-conventions/route-files-v2#optional-segments).
Testing:
1. `mkdir "(\$foo)" && cd "(\$foo)"`
2. create a lua file and paste in 
```lua
require("plenary.job")
:new({
command = "ls",
cwd = vim.loop.cwd(),
})
:sync()
```
3. `:w` followed by `so %` 
On `master` this will throw an error.
=> fix(job): escape cwd path

lua/plenary/path.lua
A URI scheme can contain "-", "+" and "*" as well as digits and letters.
https://www.rfc-editor.org/rfc/rfc3986#page-17
=> Make is_uri accept all valid schemas

lua/plenary/log.lua
Justification: Allow write logs into directory `stdpath(data)` like lsp and telescope or VimBeGood.
=> feat(log): allow arbitrary logging file paths

lua/plenary/curl.lua
Hey,
In some situations, when the request is a long stream request (`--no-buffer`), it might be handy to kill/shutdown the curl request (aka job). In this way, we can use the curl like:
```
local handler
handler = curl.post({
url = "https://exampleai.fo/chat/completions",
raw = { "--no-buffer" },
headers = {
content_type = "application/json",
},
body = vim.json.encode(data),
stream = function(_, chunk)
vim.print(chunk)
end,
on_error = function(err, _, _)
return on_complete(err, nil)
end,
})
-- keymap <C-x> shutdown the long/unneeded stream
handler:shutdown()
```
=> feat(curl): return job instance if the request is stream or callback

README.md, doc/plenary-test.txt, lua/plenary/test_harness.lua
Previously, when running `PlenaryBusted` commands, all plugins were being loaded.
`{ minimal = true }` wouldn't work either because plenary must be loaded, `--noplugin` would prevent that.
`{ minimal_init = path }` had the same problem.
Solution:
- minimal by default
- `minimal` and `minimal_init` are still recognized and will have the effect of adding the `--clean` argument, but most of the times they can be omitted
- `minimal_init` will still be sourced
- `minimal` is the same as no options, so it can be omitted
- additional 'init' option, that doesn't use `--clean`
- in any case, plenary directory is always added to the rtp, so no need for the user to do that
I couldn't make it work in Windows though (neither before).
=> Tests: use minimal configuration by default

lua/plenary/job.lua, tests/plenary/job_spec.lua
I use both `plenary.popup` and `plenary.job` in my plugin [please.nvim](https://github.com/marcuscaisey/please.nvim) to [run a command in a popup terminal](https://github.com/marcuscaisey/please.nvim/blob/9a9068c75218372c4e962f364e3c8ee559c9d5d5/lua/please/runners/popup.lua#L49) and map `q` to close the popup / shutdown the job like this (simplified, [actual code here](https://github.com/marcuscaisey/please.nvim/blob/05d94392a18d8d094347100e7fcacb135701e422/lua/please/runners/popup.lua#L166-L184)):
```lua
vim.keymap.set('n', 'q', function()
close_windows()
job:shutdown()
end, { buffer = term_bufnr })
```
The editor becomes unresponsive for a second after pressing `q` (and therefore calling `Job:shutdown`). Here's a minimal example which demonstrates this:
```lua
local Job = require …
```
=> fix(job): remove freeze after shutdown is called

README.md
The README only showed the command to raise the limit on the number of open files (`ulimit`). I added the command for macOS (`sudo launchctl`), as it can be difficult to find. This is especially needed for macOS because the default limit hearkens back to the weak computers of yore and has never been updated so it's extremely low for modern computers.
My linter I have set up in null-ls also ran, which wrapped the Markdown to make it easier to read. If that's a problem I can try to change it back.
=> feat: Add file limit command for macOS to README

.gitignore, README.md, doc/plenary-test.txt, lua/plenary/test_harness.lua
otherwise its a breaking change, see
https://github.com/nvim-treesitter/nvim-treesitter/pull/4856
=> fix(test_harness): followup to #459, dont use --clean but rather --noplugin

lua/plenary/filetype.lua
This looks to be very similar to #465
I have been encountering the below error when the filepath is an integer.
```
Error executing vim.schedule lua callback: ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:428: Error executing lua: ...al/share/nvim/lazy/plenary.nvim/lua/plenary/filetype.lua:123: attempt to index local 'filepath' (a number value)
stack traceback:
...al/share/nvim/lazy/plenary.nvim/lua/plenary/filetype.lua:123: in function 'detect_from_name'
...al/share/nvim/lazy/plenary.nvim/lua/plenary/filetype.lua:167: in function 'detect'
...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:434: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:428>
[C]: in function 'nvim_buf_call'
...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:428: …
```
=> fix(filtetype.lua): don't fail on integer filepath

lua/plenary/curl.lua
I was using plenary.nvim on a non-major operating system (Android in case you wanna know) where `/temp` isn’t accessible. I believe many people who uses nvim on Android will find this useful. Also, there’s no android specific code. So hope it won’t hurt getting merged.
=> feat(curl): use `XDG_RUNTIME_DIR` if available

lua/plenary/iterators.lua, tests/plenary/iterators_spec.lua
I often need these and end up implementing them myself, so thought they'd be useful to have in here.
=> feat: add `Iterator:fold` and `Iterator:enumerate`

lua/plenary/iterators.lua
Super small - `Se` should probably be `See`.
=> Fix spelling in comment in iterators.lua

lua/plenary/job.lua
Looks like vim is doing regex string parsing when using `expand` so when using have paths that represent some invalid regex, an error is thrown.
In this particular case, the invalid regex came in the form of reverse range: `:expand("[z-a]")` will error out.
partially fixes https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/289
=> fix(job): escape square brackets `[]` from being expanded

lua/plenary/path.lua
According to #481 , and https://www.rfc-editor.org/rfc/rfc3986#page-17,
>Scheme names consist of a sequence of characters beginning with a
>letter and followed by any combination of letters, digits, plus
>("+"), period ("."), or hyphen ("-").
#481 not actually fix it, and caused other problems like is_uri not accept `jdt://` uri. this PR is a patch of it.
=> fix: is_uri not accept all valid schemas

lua/plenary/async/control.lua, tests/plenary/async/condvar_spec.lua
Hi guys, I found that the condvar break in the following logic
```lua
local condvar = async.control.Condvar.new()
async.run(function()
condvar:wait()
end)
async.run(function()
condvar:wait()
end)
condvar:notify_all()
async.run(function()
condvar:wait()
end)
-- break: The coroutine failed with this message: cannot resume dead coroutine
condvar:notify_all()
```
After some deeper research, I found that notify_all uses an index to empty the table inside the loop, but misses some elements due to index changed.
=> fix: ensure that handlers are emptied after notify_all

lua/plenary/profile/p.lua
neovim 0.10 has bumped up LuaJIT version, which makes plenary.profile
fail to work due to the "LuaJIT core/library version mismatch" error.
We can have an allowed range for `jit.version_num` as 20100~20199.
FYI, `require('jit')` reports:
nvim-0.9.1:
version = "LuaJIT 2.1.0-beta3",
version_num = 20100
nvim-0.10.x (HEAD version as of today, an example):
version = "LuaJIT 2.1.1693268511",
version_num = 20199
=> fix: support LuaJIT versions with neovim 0.10.x and 0.9.2

lua/plenary/busted.lua, lua/plenary/test_harness.lua, plugin/plenary.vim
This bug where Windows file paths that contain backslashes trigger an invalid escape sequence error was reported in issue #480.
This PR provides a solution for this escape sequence issue by:
- Changing the args string in plugin/plenary.vim to be a raw Lua string instead of using quotes like a regular string
- Performing a gsub to replace all backslashes with forward slashes in the functions called by the Plenary commands where the result of `vim.fn.expand` is passed as an argument (i.e. `plenary.busted.run` and `plenary.test_harness.test_directory`.
=> Resolved invalid escape sequence error caused by Windows backslash in filepaths.

.luacheckrc, lua/plenary/fun.lua, lua/plenary/functional.lua, lua/plenary/vararg/rotate.lua, scripts/vararg/rotate.lua, tests/plenary/functional_spec.lua, tests/plenary/rotate_spec.lua
The `vararg.rotate`, and both `functional.partial` and `fun.bind` (which are the same), had couple mistakes. I'll mention the particular bugs in the diff. For a reference, see: https://www.lua.org/manual/5.4/manual.html#3.4.12.
These fixes make the functions generally correct. Since these bugs have been there from the beginning, the real use is more limited (i.e. bind a single ~~(non nil)~~ parameter, or rotate 1-16 arguments). So another valid fix would be to limit the generality to these already working cases.
Let me know if that would be preferable.
Also let me know if there is some convention I've missed, or if you would like me to document this also on the issues.
=> Fix couple bugs with multiple results and varargs (...)

lua/plenary/log.lua, lua/plenary/popup/init.lua
The current build creates `outfile` such as `c:\path\to/plenary'. It has mixed separators with `\` and `/`, so `io.open` failes in Windows. This makes `plenary.log` work in Windows.
=> fix: use robust way to create path

lua/plenary/job.lua
Improve the types using [`lua-language-server annotations`](https://luals.github.io/wiki/annotations/)
- make them as specific as possible
- indicate the optional fields
- added interactive field which was left undocumented (?)
- Comments are all capitalized and space separated from the type (some comments line length would be to long if aligned)
=> Improve `lua-language-server` annotations of `Job` class

lua/plenary/busted.lua, lua/plenary/test_harness.lua, plugin/plenary.vim
According to issue #480, the `PlenaryBustedDirectory` and `PlenaryBustedFile` commands cause a visual bug because they are being run as if they are in headless mode, although they are not. 
This PR refactors thetesting and floating window logic out into a separate internal function, `_test_paths`, which tests the paths it is provided according to the `opts` it's passed and displays the results via stdout or a floating window depending on whether or not Neovim is being run headlessly.
Additionally, users would rely on the keymap `<Plug>PlenaryTestFile` to run tests from within a Neovim instance. This is supposed to display test file results in a floating window, but this would also cause a visual glitch due to using the `plenary.busted.run` command directly, instead of being scheduled by …
=> Fix for Plenary test harness floating results Window

lua/plenary/async/util.lua
When I ran this code, I got an error below.
```lua
async.util.block_on(function()
async.util.sleep(4000)
end)
print "done"
```
```bash
E5113: Error while calling lua chunk: /tmp/hoge.lua:4: bad argument #1 to 'block_on' (table expected, got nil)
stack traceback:
[C]: in function 'block_on'
/tmp/hoge.lua:4: in main chunk
```
This means the func is terminated by `vim.wait` and the variable `ret` is still `nil`. So `unpack(ret)` raises an error.
This PR fixes this bug by setting a default value for `ret`.
=> fix: avoid error when it exceeds timeout

lua/plenary/async/util.lua, tests/plenary/async/util_spec.lua
It is annoying that we should create async functions to use `async.util.run_first`. I added `async.util.race` to run simple functions concurrently. `async.util.join` also accepts simple functions instead of async ones, so it is reasonable to use the same signature, I think.
```lua
local function sleep(msec)
return function()
a.util.sleep(msec)
return msec
end
end
local funcs = vim.tbl_map(sleep, { 200, 400, 300, 100 })
a.util.join(funcs)  --> { 200, 400, 300, 100 }
a.util.race(funcs)  --> 100
```
=> feat: add async.util.race to run funcs in race

lua/plenary/curl.lua
Convert `http_version` values to `curl` command-line arguments
This PR modifies the code to enable the conversion of `http_version` values into appropriate command-line arguments for `curl`. Specifically, it converts `HTTP/0.9`, `HTTP/1.0`, `HTTP/1.1`, and `HTTP/2` to `--http0.9`, `--http1.0`, `--http1.1`, and `--http2.0`, respectively.
This enhancement allows `curl` users to conveniently specify the desired HTTP version. They can now use the `--http0.9`, `--http1.0`, `--http1.1`, and `--http2.0` parameters to specify a particular HTTP version.
Please review and merge this PR. Thank you!
=> feat(curl): add 'http_version' option, fix #394

lua/plenary/async/api.lua
This enables to return results from `async.api.*`. This is useful you call funcs such as `vim.api.nvim_get_current_buf()`.
```lua
local buf = async.api.nvim_get_current_buf()
print(buf) -- print no string in the master, but `1` in this PR build.
```
=> fix: return the results from async.api.*

lua/plenary/log.lua
This fixes an issue introduced by https://github.com/nvim-lua/plenary.nvim/pull/521 where it no longer appends `.log` to the filename breaking some plugins when there's also a folder with the same name.
=> Re-add .log extension to plugin bases logfile name

lua/plenary/path.lua
In Windows, doing `Path:new("C:\\Users"):parents()` results in a getting `C:` as one of its parents which is not a valid path. All valid paths in Windows, Linux, Mac must have at least one path separator.
Partially fixes https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/285
=> fix(path): Windows parent root directory

lua/plenary/curl.lua
There are two major problems when supplying `opts.stream` for curl methods:
1. curl methods produce junk in temp folder. Curl command dumps
headers to some file in tmp folder and cleans it up only in the
`parse.response()` method. This method is not called if 
`opts.stream` is set
2. there is no way to access response code, because it is also written to
the headers dump file in temp folder.
This PR address both of those problems by setting `job.on_exit` callback
even if `opts.stream` is provided. Methods themselves still return job, but
now user has an option to also set `opts.callback` to inspect the response
and curl cleans up the junk in temp folder
=> fixup: stream option handling in curl

lua/plenary/path.lua
Currently, Windows-style paths such as `C:\Users\<user>\*` are considered absolute paths.
However, paths such as `C:/Users/<user>/*` are used in some windows environments.
For example, in https://github.com/nvim-lua/plenary.nvim/issues/456, `C:/Users/myhome/my/local/obsidian/repo/` is used as a path.
Current implementation do not consider `C:/Users/myhome/my/local/obsidian/repo/` as an absolute path.
As a result, the cwd path (`C:\Users\myhome\AppData\Local\nvim\lua`) is prepended.
This PR should fix this problems and https://github.com/nvim-lua/plenary.nvim/issues/456.
=> fix(path): add a windows style path pattern to is_absolute()

lua/plenary/popup/init.lua, tests/plenary/popup_spec.lua
If running something like:
```lua
vim.o.modifiable = false -- remove this line and it will work.
require("plenary.popup").create("A popup", {})
```
Throws the following error and doesn't create a popup:
With these changes, it creates the popup without throwing an error.
Tests results:
```txt
========================================
Testing:        /Users/aome/dev/nvim_plugins/plenary.nvim/tests/plenary/popup_spec.lua
Success ||      plenary.popup can create a very simple window
Success ||      plenary.popup can create a very simple window after 'set nomodifiable'
Success ||      plenary.popup can apply a highlight
Success ||      plenary.popup can create a border
Success ||      plenary.popup can apply a border highlight
Success ||      plenary.popup can ignore border highlight with no …
```
=> fix(popup): create popup after `set nomodifiable`, closes #570

lua/plenary/log.lua
When the number was 0, it was trying to use `round(number, increment)` to floor the number 0, resulting in -0.
I added and if statement that returns the number if it is 0, so it doesn't try to round it.
Tested with the case provided in #569.
```lua
local M = {}
local my_hash = {
args = "!p4print checker.sv",
bang = false,
count = -1,
fargs = { "!p4print checker.sv" },
line1 = 2,
line2 = 2,
mods = "",
name = "Redir",
range = 0,
reg = "",
smods = {
browse = false,
confirm = false,
emsg_silent = false,
hide = false,
horizontal = false,
keepalt = false,
keepjumps = false,
keepmarks = false,
keeppatterns = false,
lockmarks = false,
noautocmd = false,
noswapfile = false,
sandbox = false,
silent = false,
split = "",
tab = -1,
unsilent = false,
verbose = -1,
vertical = false
}
}
local log = …
```
=> fix(log): print `-0` when `number = 0`, closes #569

lua/plenary/path.lua
When there is no file to be found `find_upwards` gets stuck in an infinite-loop.
This PR should address this.
=> fix(path): make find_upwards stop at root

lua/plenary/curl.lua
ref: https://github.com/kawre/leetcode.nvim/issues/44
TLDR: if you use `msys` curl on windows, and use -d with a path to a payload file, `msys` will not make the command execute unless you wrap the payload with `'`. I guess the simplest solution to this is to have an option to specify custom curl bin path, so if the user still wishes to use `msys` as the default curl, they still have an option to specify for example `cygwin` as the curl that `plenary.nvim` will use.
=> feat: option to use custom curl bin

.github/workflows/default.yml
Bump 0.9 release to final
Add explicit 0.10 tests now its not nightly
=> ci: bump ci versions

lua/plenary/async/util.lua
When no async functions are supplied, it will be stuck because rx() waits forever. This diff fixes it.
=> fix: return early to avoid errors with no asyncfns

lua/plenary/job.lua
spotted this while discussing with @dceluis
https://github.com/chottolabs/kznllm.nvim/pull/26#discussion_r1760595621
=> chore: fix typo in annotation for enable_recording

lua/plenary/json.lua, tests/plenary/json_spec.lua
This adds an additional feature to the `json_strip_comments` function that adds more compatibility for converting a JSON string to something compatible with `vim.fn.json_decode`. I also added tests to make sure things like commas in strings are fully ignored and that it doesn't mess up the already existing comment stripping.
Resolves #612
=> feat(json): add abliity to remove trailing commas while stripping comments

lua/plenary/job.lua, tests/plenary/job_spec.lua
The current condition prematurely quits processing of data in on_output
in some edge-cases.
In these cases `job:result()` will have all data, but not everyting was
sent through the `on_output` pipes.
Closes https://github.com/nvim-lua/plenary.nvim/issues/634
Thanks for your support, please let me know your thoughts!
=> fix: process all data on_output, even when not terminated with newline

lua/plenary/curl.lua
The response headers can have multiple steps in them, example:
"HTTP/1.1 200 Connection established",
"",
"HTTP/1.1 400 Bad Request",
"Content-Security-Policy: default-src 'none'; sandbox", "Content-Type: text/plain; charset=utf-8",
"Strict-Transport-Security: max-age=31536000",
"X-Content-Type-Options: nosniff",
before this would be reported as 200 incorrectly instead of 400 bad request. this fixes that issue
=> curl: Fix response status parsing

lua/plenary/async/uv_async.lua
`uv.fs_opendir` has an odd signature that has `callback` not in the last position. This patch enables to use `async.uv.fs_opendir` by a small hack to exchange arguments between `entries` and `callback`.
=> feat: enable to wrap uv.fs_opendir()

data/plenary/filetypes/builtin.lua
Added a new filetype for the cairo language: https://www.cairo-lang.org/
Telescope without filetype:
Telescope with the filetype:
=> feat: add cairo language filetype

lua/plenary/log.lua
Neovim has had a standard path for log files since `v0.7.0-322-g78a1e6bc0` (note this is *after* v0.7.2; the `git describe` output is a touch misleading), so this should be the preferred location. Logs aren't cache data, so they shouldn't be stored with cache data.
Given that plenary is used in a lot of plugins, this would be a tiny but free improvement in correctness for many plugins out there.
Related: #93, #487.
Fun fact: #93 was merged just 6 months before `stdpath('log')` landed!
=> fix(log): Use `stdpath('log')`

data/plenary/filetypes/base.lua
one-liner so that plenary.get_filetype('something.cppm') returns "cpp".
=> feat(filetypes): add cppm filetype

lua/plenary/curl.lua, tests/plenary/curl_spec.lua
=> Fix curl url reuse

lua/plenary/path.lua, tests/plenary/path_spec.lua
~~The prior implementation had several implementation issues which caused an infinite loop if the search turned up empty.~~
This new implementation corrects the bounds check to stop searching once we've searched everywhere we can, and properly searches the root directory.
=> fix(path): make find_upwards() search root

lua/plenary/popup/init.lua, lua/plenary/window/border.lua
neovim 0.11 introduced winborder: https://github.com/neovim/neovim/pull/31074 
This means that the user may override the global window border for all windows for which the border wasn't explicitly set.
In the past we achieved borderless windows by not specifying a border, but with winborder, the user may set the border and then the UI looks broken. So now we explicitly say that we want no border on the windows where we intended it so.
I tested this commit on neovim 0.10.2 as well, without issues.
To reproduce the issue on neovim 0.11, run:
```
:lua vim.o.winborder = "rounded"
```
and for instance open telescope, which is a plenary-using plugin showing the issue.
fixes https://github.com/nvim-telescope/telescope.nvim/issues/3436
note that i do NOT have a clear vision of the whole plenary …
=> fix: handle winborder in neovim-0.11
