lua/plenary/neorocks.lua
=> minor fix, neorocks activation on non-posix shells

CHANGELOG.md, lua/plenary/neorocks.lua, lua/plenary/popup.lua, lua/plenary/run.lua, lua/plenary/test_harness.lua, lua/plenary/window/border.lua, lua/plenary/window/float.lua, scratch/window_test.lua
=> buf -> bufnr, win -> win_id (and function style in window.float module)

.github/workflows/default.yml, Makefile
Nobody saw that 🤣 
Edit: Seems to work: https://github.com/Conni2461/plenary.nvim/actions/runs/416316772
=> ci changes and remove appimage

Makefile, README.md, lua/plenary/test_harness.lua, plugin/plenary.vim
```lua
require'plenary.test_harness'.test_directory(dir, {})
```
=> Add opts to the test harness 

lua/plenary/job.lua
Resolves lewis6991/gitsigns.nvim/issues/35
=> Job: Ignore wildignore when resolving cwd

README.md
=> Document plenary.filetype

lua/plenary/curl.lua, tests/plenary/curl_spec.lua
Changes:
- Refactor and minimize code duplication and unnecessary assignment statements.
- Fix asynchronous test/example.
- Enable users to pass table in addition to url + table
- Add request tests.
- Add description of how curl wrapper works at the top of curl.lua file.
=> refactor: curl module

lua/plenary/filetype.lua
Fix the crash mentioned here https://github.com/nvim-telescope/telescope.nvim/issues/410
=> Fix crash when directory is passed

data/plenary/filetypes/builtin.lua
=> Add support of jsx/tsx extensions

lua/plenary/scandir.lua
We need to find a way to get name from id under macos 🤔 
It would be nice if you can help me make it work on mac os :) i have read about `dscl` a couple of times that suppose to give me that output. I didn't want to invoke a different process but it seems that thats the only option on macos. Am i right? 
There is this `dscl . -list /Users UniqueID` or maybe i can call a c function?
Edit: There is `getpwuid` in linux at least. Can you check if something like this works on macos. You might need to change the 1000 to your id :) If something like this works i can find a proper solution for both linux and mac, which would be amazing
The first one will print your user name to your uid the second one your group name to your gid
```c
#include <pwd.h>
#include <grp.h>
#include <stdio.h>
int …
```
=> Fix ls for macos

lua/plenary/scandir.lua
Fixes those test: https://github.com/nvim-telescope/telescope.nvim/pull/463/checks?check_run_id=1758765074
Now i hate ffi :) and i swear i am done fixing stuff for ls 😆 
CC @tami5
=> fix: telescope tests

lua/plenary/path.lua, lua/plenary/scandir.lua, tests/plenary/path_spec.lua
Also:
- adds typ(file or directory) to scandir on_insert callback
- adds missing permission: ls fails when a permission is set to 0
Still todo:
Should be done. Is anyone missing something? I am open for suggestions / feature requests :)
Edit: might need to test windows
CC @tami5
=> Adds mkdir parents, touch and rm to path.

README.md
3182878a3f11ca1e38f3a225fc310f6ed0298d78 removed full busted and luaunit
=> Remove outdated `Bundled with` from README

lua/plenary/path.lua, lua/plenary/scandir.lua
Thanks to sunjon for reporting :)
=> fixes: for telescope.file_browser

lua/plenary/window/border.lua
Could have done this like last week. Wasn't even hard. I just have no clue about that ui/popup code base :rofl: 
CC @mjlbach i probably won't open a PR in your project, so you are allowed to copy it yourself. When its merged :)
Demo: https://streamable.com/n3b8aq
=> feat: change border title on the fly

lua/plenary/popup.lua
See https://github.com/neovim/neovim/pull/13875. Switching over the commented out code so that we don't face troubles when uncommenting it
=> Prefer vim.api over vim.fn

README.md, TESTS_README.md
Hopefully some helpful test examples as a guide on structure and using luassert mocking modules etc.
=> some test examples

lua/plenary/async_lib/async.lua
tj merged the pr before I had a change to commit this one
=> use vararg instead of packing and unpacking tables

lua/plenary/job.lua, tests/plenary/job_spec.lua
I know there are plenty of other that could possibly return self, but I
wanted to just throw this out there as a starting point.
=> feat(api-signature): Jobs after return self

data/plenary/filetypes/builtin.lua, tests/plenary/filetype_spec.lua
Please see https://github.com/nvim-telescope/telescope.nvim/issues/721 for more information. I tried the solution @Conni2461 suggested and it did fix the issue.
=> Fix shebang detection for bash

lua/plenary/async_lib/util.lua, tests/plenary/async_lib/semaphore_spec.lua
Fix counting semaphore around blocking threshold.
Add some test cases to cover basic behavior around blocking threshold.
cc @oberblastmeister
=> fix: semaphore counting

lua/plenary/window/border.lua
ref: https://github.com/nvim-telescope/telescope.nvim/issues/821
=> fix: floats for telescope

lua/plenary/scandir.lua
Close https://github.com/nvim-telescope/telescope.nvim/issues/884
=> fix: check if getpwuid or getgrgid return null

lua/plenary/profile.lua
=> fixup(profile) fix profile.stop

lua/plenary/class.lua
from https://github.com/rxi/classic
=> class abstraction from rxi/classic

lua/plenary/bit.lua, lua/plenary/path.lua
Fixes: https://github.com/nvim-lua/plenary.nvim/issues/198
=> feat: Add bit compat layer

plenary.nvim-scm-1.rockspec
plenary is a common dependencies across plugins. Using luarocks may alleviate the need for users to specify their plugins dependencies in their plugin manager (e.g., vim-plug or packer).
=> feat: added rockspec

README.md, lua/plenary/test_harness.lua
=> Allow for sequential busted-style tests.

README.md
this is just for the readme, there will be actual docs also
=> add some simple docs to readme

data/plenary/filetypes/builtin.lua
Added [racket](https://racket-lang.org/) filetype.
=> Add racket filetype

lua/plenary/test_harness.lua
=> Add timeout option to test harness

lua/plenary/log.lua
Issue #246 added the option to log to the quickfix list.
Enabled with a new config option `use_quickfix` set to false by default.
=> Added the option of logging to the quickfix list

lua/plenary/popup/init.lua, tests/plenary/popup_spec.lua
Fixes nvim-telescope/telescope.nvim#1596
@mrjones2014 does this fix your issue?
=> fix: change `EndOfBuffer` highlight for popups

lua/plenary/curl.lua
=> fix: curl args parsing

lua/plenary/path.lua
=> fix: readbytesrange on windows

lua/plenary/path.lua, tests/plenary/path_spec.lua
fix https://github.com/nvim-telescope/telescope.nvim/issues/1833
=> fix: path normalize with one char directories

lua/plenary/busted.lua
=> fix: busted things: print should now always print and errors should fail test suite

data/plenary/filetypes/builtin.lua
Sorry, had to create a new branch.
[See also #359 ](https://github.com/nvim-lua/plenary.nvim/pull/359)
=> feat: add purescript filetype

lua/plenary/path.lua
=> Corrects issue with glob missing lowercase drive letters

tests/plenary/job_spec.lua
Fix a couple of broken tests in macos. Please see included comments.
=> fix(tests): switch to macos compatible commands

README.md, lua/plenary/async/control.lua, tests/plenary/async/channel_spec.lua
fix #315
there was an issue with `Condvar` which was not properly removing handles and was causing issues with `mpsc`.
also added some docs to the readme
=> fix: condvar not properly removing handles

lua/luassert/assert.lua, lua/luassert/assertions.lua, lua/luassert/compatibility.lua, lua/luassert/formatters/init.lua, lua/luassert/match.lua, lua/luassert/matchers/core.lua, lua/luassert/spy.lua, lua/luassert/state.lua, lua/luassert/stub.lua, lua/luassert/util.lua
=> chore: bump luassert to the latest master

lua/plenary/path.lua
=> fix: clean path tostring

TESTS_README.md
I'm not sure if this is the way, but I saw that this command was available, thought I'd add it in!
=> Add instructions on how to run tests

lua/plenary/popup/init.lua
=> fix(popup): add missing module name to require

.github/workflows/release.yml
@Conni2461 this worked in my fork: https://github.com/MrcJkb/plenary.nvim/actions/runs/3855395610/jobs/6570398891
=> fix(luarocks-upload): add LUAROCKS_API_KEY to workflow env

lua/plenary/async/control.lua
await was removed. The code is broken.
=> Remove deprecated await in channel.

data/plenary/filetypes/builtin.lua
I added a new filetype for R language.
Ej. Telescope with new filetype
Ej. Telescope without filetype
=> feat: add r language filetype

.github/workflows/release.yml
=> fix(luarocks-install-test): use luajit

lua/plenary/log.lua
=> Mkdir parent arg should be parents

lua/plenary/curl.lua
PR for: https://github.com/nvim-lua/plenary.nvim/issues/231
=> feat(curl): Make synchronous curl timeout configurable, PR for #231

lua/plenary/curl.lua
=> feat: add optional on_error callback. fixes #304

data/plenary/filetypes/builtin.lua
=> feat: Add smithy file type

lua/plenary/log.lua
Justification:
- The default adds 100 characters only for `[TRACE date] filepath:line`:
* [TRACE Mi 26 Apr 2023 23:06:02 CEST]
* /home/username/projects/libbuf.nvim/lua/libbuf/init.lua:133
- Typical tracing logs contain 40-50 chars for fn name and some variable
*  `currentBuffersWithPropertis():  bufprops[1] ={`
- Assumptions or purpose of the plenary.log are not documented.
=> feat(log): Allow user-customizable log messages.

README.md
Noticed the readme is hard to navigate. This just changes items in the modules list to links.
=> Add links in module list to relevant sections

lua/plenary/path.lua, lua/plenary/scandir.lua, lua/plenary/strings.lua
=> fix: ffi calls for macos

data/plenary/filetypes/builtin.lua
Added file types for [jai](https://github.com/Jai-Community/Jai-Community-Library/wiki) and hlsl (directx shaders).
=> feat: Add jai and hlsl file types

lua/plenary/curl.lua, lua/plenary/iterators.lua, lua/plenary/job.lua, lua/plenary/scandir.lua, tests/plenary/path_spec.lua
Closes #585 
Still work to do with vim.loop/vim.uv but I didn't want this PR to be too big
=> fix: 0.11 compat
